{% set version = "0.2.0" %}

package:
  name: kernax
  version: {{ version }}

source:
  url: https://gitlab.com/drti/kernax/-/archive/{{ version }}/kernax-{{ version }}.tar.gz
  sha256: a8dbe974c2d5327853cb700eb2112f5ac94db8db8410c5710fab57b09dd4408b

build:
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - jax
    - blackjax ==0.9.6
    - numpy
    - scipy
    - tqdm
    - pandas
    - matplotlib-base
    - scikit-learn
    - typing_extensions

test:
  imports:
    - kernax

about:
  home: https://gitlab.com/drti/kernax
  summary: 'Thinning MCMC outputs with kernel methods using JAX'
  description: |
    kernax is a small package based on jax that implements kernel methods
    for post-processing mcmc outputs

  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://kernax.readthedocs.io
  dev_url: https://gitlab.com/drti/kernax

extra:
  recipe-maintainers:
    - bstaber
